// Schema types for StarBear. The actual tables are created in src/lib/db/migrations/*.sql
// (generated by drizzle-kit, executed by the node:sqlite client).
// Each `Row` interface mirrors a table row.

export interface CollectionRow {
  id: string;
  name: string;
  description: string | null;
  parent_id: string | null;
  sort_order: number;
  created_at: number;
  updated_at: number;
}

export interface RequestRow {
  id: string;
  collection_id: string;
  name: string;
  method: string;
  url: string;
  headers: string;
  query_params: string;
  body_kind: string;
  body: string | null;
  auth_kind: string;
  auth_config: string | null;
  pre_script: string | null;
  post_script: string | null;
  sort_order: number;
  created_at: number;
  updated_at: number;
}

export interface EnvironmentRow {
  id: string;
  name: string;
  is_active: number;
  created_at: number;
  updated_at: number;
}

export interface EnvVariableRow {
  id: string;
  env_id: string;
  key: string;
  value: string;
  is_secret: number;
  sort_order: number;
}

export interface TestCaseRow {
  id: string;
  request_id: string;
  name: string;
  description: string | null;
  assertions: string;
  sort_order: number;
  created_at: number;
  updated_at: number;
}

export interface TestRunRow {
  id: string;
  scope: string;
  scope_ref: string | null;
  started_at: number;
  finished_at: number | null;
  status: string;
  summary: string | null;
}

export interface TestRunStepRow {
  id: string;
  run_id: string;
  step_index: number;
  request_id: string | null;
  name: string;
  status: string;
  response_meta: string | null;
  error: string | null;
  assertions_result: string | null;
}

export interface AiConversationRow {
  id: string;
  title: string;
  kind: string;
  created_at: number;
  updated_at: number;
}

export interface AiMessageRow {
  id: string;
  conversation_id: string;
  role: string;
  content: string | null;
  tool_calls: string | null;
  created_at: number;
}

export interface AiSettingsRow {
  id: string;
  active_provider: string | null;
  model_by_provider: string | null;
  encrypted_keys: string | null;
  base_url_by_provider: string | null;
  master_key_check: string | null;
  updated_at: number;
}

export interface MockServerRow {
  id: string;
  name: string;
  description: string | null;
  base_path: string;
  status: string;
  created_at: number;
  updated_at: number;
}

export interface MockResponseRow {
  id: string;
  server_id: string;
  method: string;
  path_pattern: string;
  status: number;
  headers: string | null;
  body: string | null;
  delay_ms: number;
  sort_order: number;
  created_at: number;
  updated_at: number;
}
