/**
 * Regenerate `docs/ai-agent/agent-manifest.json` and `docs/ai-agent/tool-reference.md`
 * from the live `src/lib/agent/tools.ts`. Run after adding or changing a tool.
 *
 * CI fails if these files drift from `src/lib/agent/tools.ts`.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildManifest } from '../src/lib/agent/manifests';

const manifest = buildManifest();
const outDir = resolve(process.cwd(), 'docs/ai-agent');
mkdirSync(outDir, { recursive: true });

writeFileSync(resolve(outDir, 'agent-manifest.json'), JSON.stringify(manifest, null, 2));

const md = [
  '# Tool Reference',
  '',
  `Version: \`${manifest.version}\``,
  '',
  '> This file is generated by `pnpm gen:agent-manifest`. Do not edit by hand.',
  '',
  ...manifest.tools.map((t) =>
    [
      `## \`${t.name}\``,
      '',
      t.description,
      '',
      '**Parameters:**',
      '',
      '```json',
      JSON.stringify(t.parameters, null, 2),
      '```',
      '',
    ].join('\n'),
  ),
].join('\n');

writeFileSync(resolve(outDir, 'tool-reference.md'), md);

console.log(`Wrote ${outDir}/agent-manifest.json and tool-reference.md`);
